<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.8.24">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="dcterms.date" content="2026-06-16">

<title>Using mapme.biodiversity for conflict analysis</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="Mapme-Introduction_files/libs/clipboard/clipboard.min.js"></script>
<script src="Mapme-Introduction_files/libs/quarto-html/quarto.js" type="module"></script>
<script src="Mapme-Introduction_files/libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="Mapme-Introduction_files/libs/quarto-html/axe/axe-check.js" type="module"></script>
<script src="Mapme-Introduction_files/libs/quarto-html/popper.min.js"></script>
<script src="Mapme-Introduction_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="Mapme-Introduction_files/libs/quarto-html/anchor.min.js"></script>
<link href="Mapme-Introduction_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="Mapme-Introduction_files/libs/quarto-html/quarto-syntax-highlighting-dc55a5b9e770e841cd82e46aadbfb9b0.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="Mapme-Introduction_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="Mapme-Introduction_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="Mapme-Introduction_files/libs/bootstrap/bootstrap-9e3ffae467580fdb927a41352e75a2e0.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="style.css">
</head>

<body class="fullcontent quarto-light">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Using mapme.biodiversity for conflict analysis</h1>
</div>



<div class="quarto-title-meta">

    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">June 16, 2026</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="overview" class="level1">
<h1>Overview</h1>
<p>In this tutorial, we want to learn how to construct a spatial dataset for conflict analysis using the <a href="https://www.mapme-initiative.org/"><strong>mapme.biodiversity</strong></a> package. While a little background knowledge in <em>R</em> and spatial data is helpful, we will go through all steps slowly and with detailed explanation. So don’t worry - in the end you’ll be able to replicate the steps we take here, and adjust them to your very own research question.</p>
<p>This tutorial is meant both for advanced as well as inexperienced <em>R</em> users. The main text focuses on the replicable code that you can use for your research, while all sections include lots of additional on-demand details explaining our code chunks for less experienced users.</p>
<p>Our tutorial will go through the following steps:</p>
<ol type="1">
<li><p><a href="#headline1"><strong>General Introduction</strong></a>: Here we will discuss the basics of <em>R</em> and geodata. If you are already familiar with packages and functions in <em>R</em> you can very well skip over this section and start with “Introductory Example: Iraq”. Just make sure to adopt the code snippets for your own code so that the required packages are loaded.</p></li>
<li><p><a href="#headline2"><strong>mapme.biodiversity Workflow</strong></a>: In this section, we will go through one example for a conflict analysis based on Iraq. We will draw all data from the mapme.biodiversity package, and analyze based on <em>UCDP</em> conflict event data how civil conflict in Iraq progressed over the years. Finally, we will empirically analyze what geographic characteristics correlate with conflict incidence.</p></li>
</ol>
</section>
<section id="getting-started" class="level1">
<h1><a name="headline1" href=""></a> Getting Started</h1>
<details>
<summary>
Introduction to <em>R</em> packages, objects, and functions
</summary>
<section id="how-does-r-tick" class="level2">
<h2 class="anchored" data-anchor-id="how-does-r-tick">How does <em>R</em> tick?</h2>
<p>When we work in <em>R</em>, we basically do the same thing over and over again: we use <em>functions</em> to create or manipulate <em>objects</em>. There are many types of <em>objects</em>, and we will talk about some of them.</p>
<p>Note that most user interfaces like <em>RStudio</em> allow you to either type commands in the command prompt to execute them directly, or to develop a script where you collect all commands (with a good commentary) and execute them from there. We highly recommend you to work with scripts where you develop the full workflow from reading the data to finishing your analysis. This will make your coding transparent, allow you (and your co-authors) to revisit and adjust coding steps, and make it much easier to find coding mistakes. It is therefore recommendable to use the command prompt only for testing and checking things while working on a full workflow in the script.</p>
<p>The simplest <em>objects</em> are <em>scalars</em> (i.e.&nbsp;single numbers or letters), which we can combine into <em>vectors</em> (arrays of numbers or letters). We can then combine <em>vectors</em> to a <em>matrix</em>, which is a combination of line- and row-vectors. Commonly, we will use <em>matrices</em> with some nice extra attributes. <em>R</em> calls them <em>data frames</em>. While data frames follow the same intuition as matrices by having rows and columns, they provide much more flexibility for coding. Most importantly, they allow you to store different vector classes together. For example, you can have a numeric column and a character column in the same data frame object. A matrix on the other hand forces you to convert all columns to only one class, e.g.&nbsp;character. In our workflow below we use a specific type of them called <em>simple features</em>. These will be the basic building block of our analysis.</p>
<p>We can apply all sorts of different <em>functions</em> on all sorts of <em>objects</em>. You will recognize <em>functions</em> from the parentheses. For example, <code>summary()</code> is a function which wants you to name an <em>object</em> inside the parentheses. There are a lot of <em>functions</em> that <em>R</em> already knows when you install it. Still, users keep writing many more <em>functions</em> for specific use cases. One of these use cases is working with spatial data. For this, we will need a number of additional <em>functions</em>, which we can “teach” our <em>R</em> session by loading <em>packages</em>.</p>
</section>
<section id="packages" class="level2">
<h2 class="anchored" data-anchor-id="packages">Packages</h2>
<p>Whenever you start an <em>R Script</em> to work on a project, one of the first things you’ll want to do is read the <em>packages</em> you want to use in this project.</p>
<p>If you want to use a <em>package</em> for the first time (or after you update/re-install your <em>R</em> version) you will have to install it first. This works with the <code>install.packages()</code> function, where you put a string with the package’s name in the parentheses. After a <em>package</em> is installed, you can load it at the beginning of every <em>R</em> session with the <code>library()</code> command.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="do">## You only need to install packages once (as long as you do not update your R version): </span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"tidyverse"</span>) <span class="co"># Makes data manipulation easier</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"sf"</span>) <span class="co"># Handles Spatial Objects</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"geodata"</span>) <span class="co"># Helps download spatial data</span></span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"mapme.biodiversity"</span>,<span class="at">dependencies=</span>T) <span class="co"># The core of this tutorial</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section></details>
<p>Let’s start our <em>R</em> session by loading the necessary packages. We will need the <em>mapme.biodiversity</em> package for our spatial data project to use the wealth of data generated by the <em>mapme.biodiversity</em> project. In addition, we will be using a lot of functions from the <em>tidyverse</em> and <em>sf</em> packages. Finally, the <em>geodata</em> package will help us access additional geodata that we will need to create our dataset.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Yet, you'll need to call the packages each time you start a new session: </span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(mapme.biodiversity)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(geodata)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
More on the packages we are using
</summary>
<p>You now enriched your <em>R</em> session by hundreds of new functions. Let’s quickly go through the packages we just loaded and see why we need them:</p>
<p>The <em>tidyverse</em> package is actually a collection of packages which include a large number of functions that make data wrangling in <em>R</em> easier. It is totally possible to reproduce our workflow below without any functions from the <em>tidyverse</em> package. However, <em>tidyverse</em> includes so many convenience functions that it comes close to a totally new syntax within <em>R</em> which is often much more intuitive. Other than introducing new functions like <code>select()</code>, <code>filter()</code>, or <code>mutate()</code> which save us a lot of typing, the <em>tidyverse</em> also includes the <em>ggplot</em> package that allows us to make nice maps and graphs. In addition, the <em>tidyverse</em> allows us to use pipes (<code>%&gt;%</code>). Piping allows us to call several functions one after the other, without all the time specifying anew which object we are working with.</p>
<p>The <em>sf</em> package introduces a number of functions and new object types which provide the infrastructure for working with spatial data and using <em>R</em> as a <em>GIS</em>. The name <em>sf</em> is short for “simple features.” We will see below that “simple features” are spatial vector data, i.e.&nbsp;points, lines or polygons that indicate locations and forms in space. The nice thing about the <em>sf</em> package is that it works nicely together with the usual <em>R</em> syntax. This is, we will create <em>simple features</em> below. These are normal datasets (“data frames” in <em>R</em>) with spatial information.</p>
<p>Finally, the <em>geodata</em> package pretty much does what the name says: it includes a number of functions that help us download geodata from the internet. We will here specifically use the <code>gadm()</code> function to download spatial data on countries’ administrative boundaries from the <em>GADM</em> project’s homepage.</p>
</details>
</section>
<section id="starting-your-project" class="level2">
<h2 class="anchored" data-anchor-id="starting-your-project">Starting your project</h2>
<p>With our packages loaded, we are pretty much good to go. Let’s start our <em>R Session</em> by:</p>
<ol type="1">
<li>Clearing our <em>Workspace</em> to avoid objects from other projects interfering with our work here.</li>
<li>Setting the <em>Working Directory</em> to tell <em>R</em> where to find and store your data.</li>
</ol>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="do">## It is generally good practice to always start your R sessions like this: </span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="fu">rm</span>(<span class="at">list=</span><span class="fu">ls</span>()) <span class="co"># Clean for Workspace</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>main.wd <span class="ot">&lt;-</span> <span class="st">"C:/User/Documents/MapMe"</span> <span class="co"># Define your Working Directory. </span></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co">#NOTE: Don't forget switching backward-slash (\) to forward slash (/). </span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a><span class="fu">setwd</span>(main.wd) <span class="co"># Set the Working Directory.</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
What does this do?
</summary>
<p>It makes sense to always start your sessions like this. Clearing your work space is important to make sure that objects from other projects do not interfere with your current one. It is also good practice to define your working directory in the beginning and then only use <em>relative paths</em> in the rest of the script. This will allow you to easily adapt your code when using it on a new computer, and save your colleagues and co-authors a lot of headache when they want to implement your code.</p>
<p>When setting up the script, you already see the combination of <em>functions</em> and <em>objects</em> at play. For example, we use the <code>setwd()</code> function to set our working directory, i.e.&nbsp;tell <em>R</em> where to look for and store the files we want to work with. The <em>function</em> takes the <code>main.wd</code> <em>object</em> that we defined above as a string identifying a folder on our computer as the input. If you are a windows user, remember to switch everything to forward-slash, otherwise <em>R</em> will complain.</p>
</details>
<p>Instead of starting your session with emptying your environment and setting the workspace, you can alternatively <strong>create an R Project</strong>. An <em>R</em> Project provides a fully contained project space for your project, so you do not need to empty your environment. It will also automatically use the working directory where you store the <em>R</em> project. We will work with an <em>R</em> project in the accompanying tutorial for Madagascar conflict data.</p>
</section>
<section id="headline2" class="level2">
<h2 class="anchored" data-anchor-id="headline2">Introductory Example: Iraq</h2>
<p>To get familiar with conflict data and the <em>mapme.biodiversity</em> workflow, we want to look at an example. In this example, we want to investigate where the main conflict zones are in <em>Iraq</em>, and trace the geographic spread of the “Islamic State (IS)” over time. Finally, we will ask whether certain geographic characteristics determine whether provinces in Iraq witnessed more or less conflict incidents.</p>
<p>We will base our analysis on a spatially aware <em>data frame</em> that identifies the administrative provinces in Iraq. Afterwards, we will use our <em>polygons</em> to collect data associated with them. Specifically, for each spatial unit defined by a province’s boundaries, we will collect information on conflict incidents and other relevant variables within those areas. Then finally, we can use these data for graphical visualization, with provinces as our level of analysis.</p>
</section>
<section id="step-1-get-spatial-polygon-dataset-that-defines-our-unit-of-observation" class="level2">
<h2 class="anchored" data-anchor-id="step-1-get-spatial-polygon-dataset-that-defines-our-unit-of-observation">Step 1: Get Spatial Polygon Dataset that defines our unit of observation</h2>
<p>Our analysis starts out by defining our unit of observation, i.e.&nbsp;the spatial entities for which we want to collect and analyse our variables. In technical terms, we need to get our hands on a <em>spatial vector dataset</em> that defines the spatial units we want to work with.</p>
<details>
<summary>
More on Spatial Vector Data
</summary>
<p>There are three types of vector data:</p>
<ol type="1">
<li><em>Points</em>, defined by longitude and latitude.</li>
<li><em>Lines</em>, connecting two or more points by straight lines.</li>
<li><em>Polygons</em>, a convex combination of lines.</li>
</ol>
<p>When we work with spatial data in <em>R</em>, we want to use either type of these vector data and add to each observation information that is associated with this geographic entity. For example, we could collect a number of points that identify certain locations on the globe, and then add information about the altitude and temperature for each of these very points. Note that an alternative to vector data would be a <em>raster dataset</em>, which we will not discuss here.</p>
<p>For most types of spatial analysis, <em>polygons</em> are the most helpful unit of analysis. There are a number of variables that can hardly be measured with just one point or line in space. For example, how would we think about the population or GDP of just one point on earth? In polygons however, we can measure and aggregate pretty much everything. For example, we can count the number of people in a polygon, get their average income, measure the average temperature and precipitation in that polygon, and so on.</p>
<p>This often involves spatially matching data that come as points, like conflict events, with polygons and then finding the right way of aggregation. We will do this below. If you think about it, almost all data we are confronted with everyday are collected for polygons: the population and GDP counts that e.g.&nbsp;the World Bank publishes for each country is nothing else than the aggregated number of people and incomes that fall within the border (polygons) of each country.</p>
</details>
<p>For our Iraq example, let us work with provinces (the first administrative level) as our unit of observation. We could use any other level, or even totally made-up polygons. In the end, it is only important that we supply the <em>mapme.biodiversity</em> package with some sort of polygons for data extraction. Let’s download province-polygons for Iraq from the <em>GADM</em> project.</p>
<details>
<summary>
More on GADM downloads
</summary>
<p>There are many ways to get polygons on administrative (or other) regions across the world. One option would be to use official data from the country’s statistical office that you want to work with. When you want to work with global datasets however, this can become quite tedious. Luckily, there are mapping projects like the <em>Database of Global Administrative Areas (GADM)</em> which provide collections of countries’ administrative boundaries at different resolutions.</p>
<p>Even better is that we can easily source data from <em>GADM</em> with the <code>gadm()</code> function from the <em>geodata</em> package. This function wants to know three things from us:</p>
<ol type="1">
<li>For which <em>country</em> do we want data? You can e.g.&nbsp;provide a country’s <em>ISO3 Code</em>, a standardized 3-digit code that uniquely identifies each country.</li>
<li>The <em>administrative level</em> for which you want the borders. With <code>level=1</code>, we get the first level, i.e.&nbsp;provinces. Other levels would be, e.g., the national borders (<code>level=0</code>) or the districts (<code>level=2</code>). Some countries even offer lower resolutions in sub-districts (<code>level=3</code>).</li>
<li>The <em>path</em> to store the data downloaded from <em>GADM</em>. This can just be your working directory.</li>
</ol>
<p>To find the ISO Code for the country you want to work with, you can use the <code>countrycodes</code> package (note that you’ll have to install it before using it the first time):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(countrycode)</span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">countrycode</span>(<span class="st">"Iraq"</span>,<span class="at">origin=</span><span class="st">"country.name"</span>,<span class="at">destination=</span><span class="st">"iso3c"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] "IRQ"</code></pre>
</div>
</div>
</details>
<p>Note that the <em>geodata</em> package is not a direct part of the <em>sf</em> environment with which we will be working afterwards. Therefore, we will have to convert the polygons we get from <code>gadm()</code> to the <em>sf</em> type such that our <em>sf</em> commands can work with it. This is easily done with the <code>st_as_sf()</code> command.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Use the gadm() function from the geodata package to get administrative boundaries: </span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>mp_sf <span class="ot">&lt;-</span> <span class="fu">gadm</span>(<span class="at">country=</span><span class="st">"IRQ"</span>,<span class="at">level=</span><span class="dv">1</span>,<span class="at">path=</span>main.wd)</span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a> <span class="co"># Convert to an sf object so we can use sf-functions on it:</span></span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>mp_sf <span class="ot">&lt;-</span> <span class="fu">st_as_sf</span>(mp_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
More on Simple Features
</summary>
<p>We now have a <em>simple feature</em> that we called <code>mp_sf</code>. You can think of it as a spatially aware data frame. Let’s inspect the object a bit further:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb7"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(mp_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>      COUNTRY         NAME_1            geometry 
 Length   :18   Length   :18   MULTIPOLYGON : 1  
 N.unique : 1   N.unique :18   POLYGON      :17  
 N.blank  : 0   N.blank  : 0   epsg:4326    : 0  
 Min.nchar: 4   Min.nchar: 5   +proj=long...: 0  
 Max.nchar: 4   Max.nchar:15                     </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb9"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(mp_sf)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>Simple feature collection with 6 features and 2 fields
Geometry type: GEOMETRY
Dimension:     XY
Bounding box:  xmin: 38.79684 ymin: 29.05857 xmax: 48.56856 ymax: 37.32503
Geodetic CRS:  WGS 84
# A tibble: 6 × 3
# Groups:   COUNTRY [1]
  COUNTRY NAME_1                                                        geometry
  &lt;chr&gt;   &lt;chr&gt;                                                   &lt;GEOMETRY [°]&gt;
1 Iraq    Al-Anbar     POLYGON ((44.22349 33.25313, 44.22324 33.28643, 44.22412…
2 Iraq    Al-Basrah    MULTIPOLYGON (((47.92017 30.02874, 47.93154 30.02465, 47…
3 Iraq    Al-Muthannia POLYGON ((46.53541 30.56554, 46.5242 30.57467, 46.50055 …
4 Iraq    Al-Qadisiyah POLYGON ((45.76847 31.63302, 45.76831 31.6616, 45.75977 …
5 Iraq    An-Najaf     POLYGON ((44.46421 31.93221, 44.46847 31.95859, 44.47314…
6 Iraq    Arbil        POLYGON ((43.81506 36.40563, 43.81105 36.4004, 43.81083 …</code></pre>
</div>
</div>
<p>These two functions will help you get an overview. First <code>summary()</code> gives an overview of each variable attached to the data frame, while <code>head()</code> will print the first 6 observations in your console. You could also use the <code>View()</code> function to open the full dataset in a separate window. Either way, you will see that the <code>gadm()</code> command gave us 18 different polygons which will be our unit of observation. For these 18 observations, we already have some variables attached to it right away.</p>
<p>The most important variable for us in the beginning is the very last variable, called <em>geometry</em>. This one variable holds all the spatial information <em>R</em> needs to identify each of Iraq’s provinces as a spatial entity. You see that the <em>geometry</em> variable identifies each observation as a <em>POLYGON</em> and contains the exact point coordinates that each polygon is made of.</p>
<p>We also see that <code>gadm()</code> delivered a number of other variables, i.e.&nbsp;certain part of information that are associated with each single one of our polygons. These additional variables basically give us the names (and some IDs) for each of the polygons. For example, we see that the first observation is the “Al-Anbar” province in the country of Iraq.</p>
<p>Since we are working with spatial data, there is an even more convenient way to get to know our data - we can just plot and inspect them! It is easy to quickly visualize spatial data with the <code>plot()</code> command. Note that we use the function <code>st_geometry()</code> to let <em>R</em> know that we only want to plot the boundaries and not visualize any of the data attached to the dataset (you can try yourself what happens if you do not include the <code>st_geometry()</code> function):</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">st_geometry</span>(mp_sf))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-9-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>This map very well illustrates the level of observations on which we will base our study. Now, it’s time to enrich our polygons with data for the analysis.</p>
</details>
</section>
<section id="step-2-collect-the-data-from-mapme.biodiversity" class="level2">
<h2 class="anchored" data-anchor-id="step-2-collect-the-data-from-mapme.biodiversity">Step 2: Collect the data from mapme.biodiversity</h2>
<p>The hardest part of an empirical analysis comes before the actual analysis - the collection of a dataset. Our goal is to investigate the conflict trajectories in Iraq, and analyze what local characteristics correlate with conflict incidence. This means that we want to collect a dataset that tells us, for each of Iraq’s provinces, how many conflict-related fatalities occurred, together with a number of potential local explanatory variables.</p>
<p>Here comes the power of the <em>mapme.biodiversity</em> package. Instead of downloading and matching all the data ourselves, we can use just a couple of functions to let <em>mapme.biodiversity</em> do the work for us. Whenever you want to collect a new dataset using <em>mapme.biodiversity</em>, you’ll have to go through the same simple steps. You can, of course, just use the code we develop here and adjust it, e.g.&nbsp;by downloading different polygons as the unit of analysis, or by selecting different indicators from <em>mapme.biodiversity</em> below.</p>
<p>The <em>mapme.biodiversity</em> workflow follows a couple of steps that you need to go through one by one:</p>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="576"></p>
</figure>
</div>
</div>
</div>
<p>To get data from <em>mapme.biodiversity</em>, we first need to figure out what variables we actually want. <em>mapme.biodiversity</em> includes a number of indicators from different original sources. Which ones are these? The <code>available_resources()</code> function returns a data.frame with all the resources currently available in mapme.biodiversity. To view all available indicators, we wrap the function with the <code>print()</code> function. Otherwise, <em>R</em> would only show us the first 10 indicators.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb12"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">available_resources</span>(), <span class="at">n=</span><span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 35 × 5
   name                             description             licence source type 
   &lt;chr&gt;                            &lt;chr&gt;                   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;
 1 accessibility_2000               Accessibility data for… See JR… https… rast…
 2 acled                            Armed Conflict Locatio… Visit … Visit… vect…
 3 biodiversity_intactness_index    Biodiversity Intactnes… CC-BY-… https… rast…
 4 chelsa                           Climatologies at High … Unknow… https… rast…
 5 chirps                           Climate Hazards Group … CC - u… https… rast…
 6 esalandcover                     Copernicus Land Monito… CC-BY … https… rast…
 7 fritz_et_al                      Drivers of deforestati… CC-BY … https… rast…
 8 gfw_emissions                    Global Forest Watch - … CC-BY … https… rast…
 9 gfw_lossyear                     Global Forest Watch - … CC-BY … https… rast…
10 gfw_treecover                    Global Forest Watch - … CC-BY … https… rast…
11 global_surface_water_change      Global Surface Water -… https:… https… rast…
12 global_surface_water_occurrence  Global Surface Water -… https:… https… rast…
13 global_surface_water_recurrence  Global Surface Water -… https:… https… rast…
14 global_surface_water_seasonality Global Surface Water -… https:… https… rast…
15 global_surface_water_transitions Global Surface Water -… https:… https… rast…
16 gmw                              Global Mangrove Watch … CC BY … https… vect…
17 gsw_time_series                  Global Surface Water -… https:… https… rast…
18 humanfootprint                   Time series on human p… CC BY … https… rast…
19 ipbes_biomes                     Global Assessment Repo… CC 4.0  https… rast…
20 irr_carbon                       Amount of carbon irrec… CC NC … https… rast…
21 iucn                             IUCN Species Richness … https:… https… rast…
22 key_biodiversity_areas           Key Biodiversity Areas  https:… https… vect…
23 man_carbon                       Amount of carbon that … CC NC … https… rast…
24 mcd64a1                          MODIS Burned Area Mont… https:… https… rast…
25 nasa_grace                       NASA Gravity Recovery … https:… https… rast…
26 nasa_srtm                        NASA Shuttle Radar Top… https:… https… rast…
27 nelson_et_al                     Global maps of travelt… CC-BY … https… rast…
28 soilgrids                        ISRIC - Modelled globa… CC-BY … https… rast…
29 teow                             Terrestrial Ecosystems… unknown https… vect…
30 ucdp_ged                         UCDP Georeferenced Eve… CC-BY … https… vect…
# ℹ 5 more rows</code></pre>
</div>
</div>
<p>From this data.frame, we see which data sources are currently available. We will need these names below to specify what data we want <em>mapme.biodiversity</em> to extract for us. Since we want to look at conflict incidence, the <em>ucdp_ged</em> data source denotes the main dataset we need.</p>
<p>This references the <a href="https://ucdp.uu.se/"><strong>Geocoded Event Database (GED)</strong></a> from the <strong>Uppsala Conflict Data Program (UCDP)</strong>, an event-level dataset that collects information on various types of battles worldwide. The original data come as points that identify battle locations, and <em>mapme.biodiversity</em> will directly aggregate it to the province level for us by counting, e.g., the number of battles and fatalities within each province and month. Other interesting data sources for us are, among others, the <em>gsw_treecover</em> dataset holding information on tree coverage or the <em>worldclim</em> dataset that provides information about local weather conditions.</p>
<p>Each data source provides different <em>indicators</em>. For example, we can get information on the number of conflict fatalities from the UCDP dataset. You can have a look at the different indicators that <em>mapme.biodiversity</em> supplies via the resources named above using the <code>available_indicators()</code> function:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb14"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">available_indicators</span>(),<span class="at">n=</span><span class="dv">30</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 40 × 3
   name                          description                           resources
   &lt;chr&gt;                         &lt;chr&gt;                                 &lt;list&gt;   
 1 biodiversity_intactness_index Averaged biodiversity intactness ind… &lt;tibble&gt; 
 2 biome                         Areal statistics of biomes from TEOW  &lt;tibble&gt; 
 3 burned_area                   Monthly burned area detected by MODI… &lt;tibble&gt; 
 4 deforestation_drivers         Areal statistics of deforestation dr… &lt;tibble&gt; 
 5 drought_indicator             Relative wetness statistics based on… &lt;tibble&gt; 
 6 ecoregion                     Areal statistics of ecoregions based… &lt;tibble&gt; 
 7 elevation                     Statistics of elevation based on NAS… &lt;tibble&gt; 
 8 exposed_population_acled      Number of people exposed to conflict… &lt;tibble&gt; 
 9 exposed_population_ucdp       Number of people exposed to conflict… &lt;tibble&gt; 
10 fatalities_acled              Number of fatalities by event type b… &lt;tibble&gt; 
11 fatalities_ucdp               Number of fatalities by group of con… &lt;tibble&gt; 
12 gsw_change                    Statistics of the surface water chan… &lt;tibble&gt; 
13 gsw_occurrence                Areal statistic of surface water bas… &lt;tibble&gt; 
14 gsw_recurrence                Areal statistic of surface water bas… &lt;tibble&gt; 
15 gsw_seasonality               Areal statistic of surface water by … &lt;tibble&gt; 
16 gsw_time_series               Global Surface Water - Yearly Time S… &lt;tibble&gt; 
17 gsw_transitions               Areal statistics of surface water gr… &lt;tibble&gt; 
18 humanfootprint                Statistics of the human footprint da… &lt;tibble&gt; 
19 ipbes_biomes                  Area distribution of IBPES biomes wi… &lt;tibble&gt; 
20 irr_carbon                    Statistics of irrecoverable carbon p… &lt;tibble&gt; 
21 key_biodiversity_areas        Area estimation of intersection with… &lt;tibble&gt; 
22 landcover                     Areal statistics grouped by landcove… &lt;tibble&gt; 
23 man_carbon                    Statistics of manageable carbon per … &lt;tibble&gt; 
24 mangroves_area                Area covered by mangroves             &lt;tibble&gt; 
25 population_count              Statistic of population counts        &lt;tibble&gt; 
26 precipitation_chelsa          Statistics of CHELSA precipitation l… &lt;tibble&gt; 
27 precipitation_chirps          Statistics of CHIRPS precipitation l… &lt;tibble&gt; 
28 precipitation_wc              Statistics of WorldClim precipitatio… &lt;tibble&gt; 
29 slope                         Statistics of slope based on NASA SR… &lt;tibble&gt; 
30 soilproperties                Statistics of SoilGrids layers        &lt;tibble&gt; 
# ℹ 10 more rows</code></pre>
</div>
</div>
<p>We want data on violent episodes in Iraq during the rise and decline of the so-called “Islamic State in Iraq and the Levant” (ISL). ISL declared a caliphate in Iraq in 2014, so let’s have a look at its presence from 2010 onwards. In other words, we want to extract conflict data for the years 2010-2022. We can do so using <em>mapme.biodiversity</em> in just two steps:</p>
<ol type="1">
<li>Define the resources you want to download.</li>
<li>Construct the dataset from the downloaded resources by specifying the indicators you need.</li>
</ol>
<p>We will source the conflict data from the <em>Uppsala Conflict Data Program (UCDP)</em> and use their <em>Geographic Event Dataset (GED)</em>. As we saw at the beginning of this section using the <code>available_resources()</code> function, <em>mapme.biodiversity</em> assigned the name “<em>ucdp_ged</em>” to this dataset.</p>
<p>To collect the data that we want, we only need to supply the right names to the <code>get_resources()</code> function and specify a couple of features. For each resource we want to download, we will have to <span class="math inline">\((i)\)</span> define the function to download them, and <span class="math inline">\((ii)\)</span> specify what we want to download from these resources. The function to download is simply the prefix <code>get_</code> plus the resource name. So for example, we will have to supply <code>get_gfw_treecover()</code> to download data on tree coverage. The specifities of what we want to download depends on the type of resource. Usually, we can define the version of the dataset and/or the time frame if the resource is a panel dataset.</p>
<p>Don’t worry, the <em>mapme.biodiversity</em> package provides you with an overview of what to download how for each resource. So, to find out how to download for example a dataset on UCDP conflict fatalities, we can call the resource-specific help file with <code>?</code>:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb16"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a>?ucdp_ged</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>This helpfile gives us a quick overview of the source data. It tells us that the <code>ucdp_ged</code> resource contains individual events of organized violence for the years 1989 until 2021. It also tells us that we need to use the <code>get_ucdp_ged()</code> function to download this resource, and that inside this function, we can specify which version of the dataset we want to download via the <code>version=</code> argument.</p>
<p>For a start, let’s get conflict data from the <em>UCDP GED</em> dataset, and also add some data on <em>precipitation</em> and <em>tree cover</em>. Note that <em>mapme.biodiversity</em> constructs its tree coverage indicator from two sources called <em>gfw_treecover</em> and <em>gfw_lossyear</em>, so we’ll need to download both of them:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 1: Download Resources:  </span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>sources <span class="ot">&lt;-</span> <span class="fu">get_resources</span>(<span class="at">x=</span>mp_sf, <span class="co"># Our spatial dataset </span></span>
<span id="cb17-3"><a href="#cb17-3" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">get_ucdp_ged</span>(), <span class="co"># downloading conflict data</span></span>
<span id="cb17-4"><a href="#cb17-4" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">get_worldclim_precipitation</span>(<span class="at">years =</span> <span class="dv">2017</span>, <span class="at">resolution =</span> <span class="st">"10m"</span>), <span class="co"># precipitation</span></span>
<span id="cb17-5"><a href="#cb17-5" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">get_gfw_treecover</span>(), <span class="co"># downloading tree coverage data</span></span>
<span id="cb17-6"><a href="#cb17-6" aria-hidden="true" tabindex="-1"></a>                         <span class="fu">get_gfw_lossyear</span>(<span class="at">version =</span> <span class="st">"GFC-2023-v1.11"</span>)) <span class="co"># also needed for tree coverage</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>You probably had to wait a while until <em>R</em> finished running the code above. What happened now is that <em>mapme.biodiversity</em> downloaded all the source files to your main working directory. If you want to change where <em>mapme.biodiversity</em> saves the files, you can control the directory by calling the <code>mapme_options()</code> function before the <code>get_resources()</code> function. Then you can change the directory like this: <code>mapme_options(outdir = "raw_data")</code>. Note however that a folder of the name you specify, e.g.&nbsp;“raw_data”, must already exist in your current working directory.</p>
<details>
<summary>
Notes on resource versions
</summary>
<p>Note further that basically all data sources receive regular updates from the data providers. If we do not specify anything as we did above, <em>mapme.biodiversity</em> automatically downloads the most recent version for us. Sometimes you might want to go back to earlier versions, e.g.&nbsp;to replicate a study that was conducted with an older version of the data. In that case, you can tell <em>mapme.biodiversity</em> to use an older version of a given resources by specifying, e.g., <code>version="18.1"</code> in the <code>get_ucdp_ged()</code> function.</p>
</details>
</section>
<section id="step-3-construct-your-dataset" class="level2">
<h2 class="anchored" data-anchor-id="step-3-construct-your-dataset">Step 3: Construct your dataset</h2>
<p>We can now calculate our variables of interest from the downloaded datasets with the <code>calc_indicators()</code> function. Remember above when we had a look at the available indicators with the <code>available_indicators()</code> function? From there, we know which indicators we can ask for in the <code>calc_indicators()</code> function.</p>
<details>
<summary>
More on the <code>calc_indicators()</code> function and the data aggregation process
</summary>
<p>The <code>calc_indicators()</code> function wants to know first of all the name of our data portfolio, i.e.&nbsp;the resources we downloaded. So we need to specify <code>x = sources</code> as the first argument. Next, we must specify the names of the indicators we want. We do this one by one by calling a function with the prefix <code>calc_</code> and the name of the indicator. Let’s start with extracting indicators on fatalities and precipitation, but not specify anything else.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb18"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Calculate Indicators</span></span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>our_data <span class="ot">&lt;-</span> <span class="fu">calc_indicators</span>(<span class="at">x=</span>sources,<span class="co"># x is the name of our resource package defined above</span></span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">calc_fatalities</span>(), <span class="co"># Conflict</span></span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">calc_precipitation_wc</span>(), <span class="co"># Precipitation</span></span>
<span id="cb18-5"><a href="#cb18-5" aria-hidden="true" tabindex="-1"></a>                            )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Note that the <code>calc_indicators()</code> gave us a couple of notifications. These notifications tell us that it made some data aggregation decisions for us because we did not specify anything. For example, the <em>UCDP GED</em> dataset includes information on the precision of their coding for the location and time information. This is because for some battle events, the coders were not sure where or when exactly it took place because the news reports disagree or do not provide accurate information. They therefore provide precision codes. For locations for example, <em>1</em> means the highest precision (exact location), <em>4</em> is intermediate precision (only the state where a battle occurred is known), and <em>7</em> identifies the lowest precision (only known whether an event took place on ground, air, or sea). If we do not specify the precision we want, <em>mapme.biodiversity</em> automatically selects the highest precision (i.e.&nbsp;<em>1</em>) for us.</p>
<p>Similarly, we need to make important aggregation decisions when we work with data that originally come as so-called <em>raster</em> data. Our conflict data are, just as our province polygons, <em>vector data</em>. The only difference is that the events are not polygons but points. When we compare two types of vector data, aggregation is rather easy. What happens in the background here is that <em>mapme.biodiversity</em> overlays the two vector layers, checks for each battle point in which polygon it falls, and then gives us the sum of fatalities across all points for each polygon.</p>
<p>It is not that easy with our precipitation data because these come in the <em>raster format</em>. You can think of <em>raster data</em> as a grid of many small, equally-sized cells. Here, <em>mapme.biodiversity</em> will again overlay this raster with our polygons, but then needs to make a decision how to aggregate the information of the many cells that fall into each polygon to the polygon level. Other than with points, it is not much help counting the cells. Since the raster cells are equally spaced, this would just mirror the size of our polygon.</p>
<p>Instead, we need to choose an aggregation function. For precipitation, <em>mapme.biodiversity</em> uses the <code>mean</code> function as a default. This is, we get the average precipitation amount for each polygon at each point in time. This might be the right aggregation we want, but depending on your research question you might be interested in the total amount of precipitation (<code>sum</code>), or in the maximum amount of monthly precipitation (<code>max</code>).</p>
</details>
<p>We can overwrite the default aggregation decisions <em>mapme.biodiversity</em> takes for us. For example, as we are working on the province level, the location precision level <em>3</em> of the UCDP GED dataset (“location related to a second order administrative division”) is fine enough for us. Similarly, we might want to get total precipitation inside an area instead of the average across raster cells. We can change these defaults by defining exactly what we want. Check out the notifications when running the <code>calc_indicators()</code> function to see what else you can specify. Note further that these calculations need time, and consume quite some computational capacity. If you ask for a couple of datasets, <em>R</em> might restrict the usage of RAM such that the calculations fail. In this case, increase the RAM <em>R</em> is allowed to use with the <code>options()</code> function as we do below. Adjust the first number in the <code>options()</code> function to the amount of RAM you need (<em>R</em>’s error message will tell you) and leave the other two numbers as they are:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Step 2: Calculate Indicators</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a><span class="fu">options</span>(<span class="at">future.globals.maxSize=</span> <span class="dv">600</span><span class="sc">*</span><span class="dv">1024</span><span class="sc">^</span><span class="dv">2</span>) <span class="co"># Increase RAM that R is allowed to use to 600.</span></span>
<span id="cb19-3"><a href="#cb19-3" aria-hidden="true" tabindex="-1"></a>our_data <span class="ot">&lt;-</span> <span class="fu">calc_indicators</span>(<span class="at">x=</span>sources,<span class="co"># x is the name of our resource package defined above</span></span>
<span id="cb19-4"><a href="#cb19-4" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">calc_fatalities</span>(<span class="at">years =</span> <span class="dv">2010</span><span class="sc">:</span><span class="dv">2022</span>,<span class="at">precision_location =</span> <span class="dv">3</span>), <span class="co"># Conflict</span></span>
<span id="cb19-5"><a href="#cb19-5" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">calc_precipitation_wc</span>(<span class="at">engine=</span><span class="st">"exactextract"</span>,<span class="at">stats=</span><span class="st">"sum"</span>), <span class="co"># Precipitation</span></span>
<span id="cb19-6"><a href="#cb19-6" aria-hidden="true" tabindex="-1"></a>                            <span class="fu">calc_treecover_area</span>(<span class="at">years=</span><span class="dv">2017</span>) <span class="co"># Treecover</span></span>
<span id="cb19-7"><a href="#cb19-7" aria-hidden="true" tabindex="-1"></a>                            )</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
More on the output of <code>calc_indicators()</code>
</summary>
<p>When you now inspect the newly created object <code>our_data</code>, you will notice that it looks almost the same as our object <code>sources</code>, but there are three new variables: <code>fatalities</code>, <code>precipitation_wc</code>, and <code>treecover_area</code>. These new variables are no usual variables. Instead, <em>mapme.biodiversity</em> saved the indicators we wanted along with additional important information from the source datasets as lists inside our dataframe. For example, we received information on the month and type of fatalities together with the fatality data we asked for automatically as an extra.</p>
</details>
<p>In order to receive the variables we want, we need to <em>extract the indicators</em> from the list objects attached to the <code>our_data</code> dataframe. We can do so using the <code>unnest()</code> function. Note that we need to do this separately for our three indicators. Check out the details-box below for more information why:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb20"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Extract Indicators</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>df_fatal <span class="ot">&lt;-</span> <span class="fu">unnest</span>(our_data,fatalities)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>df_precip <span class="ot">&lt;-</span> <span class="fu">unnest</span>(our_data,precipitation_wc)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>df_trees <span class="ot">&lt;-</span> <span class="fu">unnest</span>(our_data,treecover_area)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
More on the unnesting process
</summary>
<p>Let’s take a look at two of the datasets we just extracted - do you notice something?</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Look at variable names:</span></span>
<span id="cb21-2"><a href="#cb21-2" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_fatal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "COUNTRY"          "NAME_1"           "assetid"          "datetime"        
 [5] "variable"         "unit"             "value"            "precipitation_wc"
 [9] "treecover_area"   "geometry"        </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="fu">colnames</span>(df_precip)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code> [1] "COUNTRY"        "NAME_1"         "assetid"        "fatalities"    
 [5] "datetime"       "variable"       "unit"           "value"         
 [9] "treecover_area" "geometry"      </code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Check dimensions (number of rows and columns):</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df_fatal)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 25272    10</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="fu">dim</span>(df_precip)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>[1] 216  10</code></pre>
</div>
</div>
<p>The important thing to notice is that the two datasets have different numbers of observations. How can this happen if we supply the same polygon dataset to extract the data? This is because we downloaded conflic data for 13 yers, but precipitation only for 2017. When you check the column names of the <code>df_precip</code> dataset you’ll notice that it includes the variable <em>date</em>. This variable identifies the first day of each month, and the precipitation variable hence gives us the amount of precipitation for the whole month following each of the dates. We therefore have a monthly panel dataset with observations for <span class="math inline">\(18\)</span> provinces for each month in 2017. This gives us <span class="math inline">\(18 \times 9 = 216\)</span> observations.</p>
<p>Our fatality dataset <code>df_fatal</code> on the other hand has a full amount of 25,272 observations. This is has two reasons. First, we got the UCDP data for 13 years. This already makes <span class="math inline">\(18 \times 13 \times 12 = 2,808\)</span> observations. Second, <em>mapme.biodiversity</em> also aggregates the conflict data by type of violence and victim. You see at the <code>variable</code> variable that the <em>UCDP GED</em> dataset distinguishes between</p>
<ol type="1">
<li><em>State-based conflict</em>: Battles between governments and rebels.</li>
<li><em>Non-state conflict</em>: Battles between two or more non-state actors like rebel groups or militias.</li>
<li><em>One-sided violence</em>: Attacks of governments or non-state actors on civilians.</li>
</ol>
<p>and between victims:</p>
<ol type="1">
<li><em>Civilian</em></li>
<li><em>Unknown</em></li>
<li><em>Total</em></li>
</ol>
<p>We therefore observe each province in each month nine times, for each type of violence. This aggregates up to 25,272 observations. Our next task will therefore be to aggregate these data to the right level for our analysis.</p>
</details>
</section>
<section id="step-4-prepare-the-dataset-for-the-analysis" class="level2">
<h2 class="anchored" data-anchor-id="step-4-prepare-the-dataset-for-the-analysis">Step 4: Prepare the dataset for the analysis</h2>
<p>So, we now have three datasets at the province-month level, giving us the total amount of precipitation for each province-month, the number of fatalities for each province-month <em>and</em> type of violence/victim, and a province-level dataset for tree coverage. Our next task will be to bring the three together.</p>
<p>While monthly data are quite nice, we very often see empirical analyses done at the yearly level. So one way would be to aggregate our data at the yearly level. However, we downloaded the precipitation data only for 2017, and the tree coverage data is only a cross section. So we will limit ourselves to a province-level cross section here and aggregate everything to the province level. You can easily expand the data to a yearly panel if you include the year variable that we construct below in the <code>group_by()</code> function during the aggregation process.</p>
<p>In addition, we need to take care of the additional <em>type of violence</em>-dimension in the conflict data. Since our precipitation indicator does not vary by type of violence (how would it?), it is empirically difficult to directly link them. Here, we need to make a judgement-call and decide what we are interested in.</p>
<p>Do we want to look at only one type of violence, e.g.&nbsp;because we are mainly interested in how the emergence of <em>ISL</em> affected violence against civilians? Then we can filter our dataset to this one type of violence. Or do we want to look at the total amount of battles and fatalities? Then we can aggregate the three types of violence and victims together. For your specific use case, you should think about which alternative suits your research question the best.</p>
<p>For the sake of demonstration, we will do both here. This is, we will construct separate variables for the number of fatalities by each type of violence and victim <em>as well as</em> in total, and append them to the same dataset.</p>
<p><strong>Preparation of the Fatalities Data</strong></p>
<p>Let’s start with the fatalities data. The first thing we’ll do is to get the year-information, and then aggregate everything to the yearly level. We will drop this temporal dimension later when we add information from the other datasets. Yet, if you download e.g.&nbsp;precipitation data also for several years, you can adapt the code to construct a panel dataset. Let’s start by converting days to years to start the aggregation:</p>
<details>
<summary>
More on date conversion
</summary>
<p>The datetime-variable is in the <em>Date</em> format. We can easily convert it to years with the <code>format()</code> function. This function takes a variable of type <em>Date</em> and changes its format, which we specify as the second argument. By specifying <code>"%Y"</code>, we tell it to return the years only. We could also get the year-month format, for example, by specifying <code>"%Y-%m"</code>. Let’s also convert the <em>Date</em> variable to <em>numeric</em>, this will make it easier to work with it later:</p>
</details>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a>df_fatal<span class="sc">$</span>year <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(df_fatal<span class="sc">$</span>datetime,<span class="st">"%Y"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>The next step is to collapse the data, i.e.&nbsp;aggregate all information to the level of analysis that we want to work at. We will have to do this once for all types of violence together (to get the total severity of conflict), and then again for each type of violence separately. We will use a loop for the ladder which is a bit more advanced coding. See the additional details below for a step-by-step guide on the loop. Note also that we remove the geometry feature with <code>st_set_geometry(NULL)</code>. Geometries are much harder to handle for <em>R</em> than simple data frames. Therefore, this also significantly speeds up the computation time.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Aggregate across all types, i.e. only at province-year level:</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> df_fatal <span class="sc">%&gt;%</span> </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_geometry</span>(<span class="cn">NULL</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COUNTRY,NAME_1,year) <span class="sc">%&gt;%</span> </span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_fatalities =</span> <span class="fu">sum</span>(value,<span class="at">na.rm=</span>T))</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="do">## Now loop through the three types of violence, aggregate, and append to the dataset: </span></span>
<span id="cb30-8"><a href="#cb30-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-9"><a href="#cb30-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Get a vector with types of violence</span></span>
<span id="cb30-10"><a href="#cb30-10" aria-hidden="true" tabindex="-1"></a>violence_types <span class="ot">&lt;-</span> <span class="fu">unique</span>(df_fatal<span class="sc">$</span>variable) </span>
<span id="cb30-11"><a href="#cb30-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb30-12"><a href="#cb30-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Here comes the actual loop: For each type of violence and victim, we 1) subset, 2) aggregate, 3) rename, and 4) append:</span></span>
<span id="cb30-13"><a href="#cb30-13" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (i <span class="cf">in</span> <span class="fu">seq_along</span>(violence_types)) {</span>
<span id="cb30-14"><a href="#cb30-14" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Subset to observations for each type of violence. </span></span>
<span id="cb30-15"><a href="#cb30-15" aria-hidden="true" tabindex="-1"></a>  <span class="co"># We also need so specify st_set_geometry(NULL). See explanation in the text below:</span></span>
<span id="cb30-16"><a href="#cb30-16" aria-hidden="true" tabindex="-1"></a>  tp <span class="ot">&lt;-</span> df_fatal <span class="sc">%&gt;%</span> </span>
<span id="cb30-17"><a href="#cb30-17" aria-hidden="true" tabindex="-1"></a>    <span class="fu">filter</span>(variable <span class="sc">==</span> violence_types[i]) <span class="sc">%&gt;%</span> </span>
<span id="cb30-18"><a href="#cb30-18" aria-hidden="true" tabindex="-1"></a>    <span class="fu">st_set_geometry</span>(<span class="cn">NULL</span>)</span>
<span id="cb30-19"><a href="#cb30-19" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Aggregate, just as above: </span></span>
<span id="cb30-20"><a href="#cb30-20" aria-hidden="true" tabindex="-1"></a>  tp <span class="ot">&lt;-</span> tp <span class="sc">%&gt;%</span> </span>
<span id="cb30-21"><a href="#cb30-21" aria-hidden="true" tabindex="-1"></a>    <span class="fu">group_by</span>(COUNTRY,NAME_1,year) <span class="sc">%&gt;%</span> </span>
<span id="cb30-22"><a href="#cb30-22" aria-hidden="true" tabindex="-1"></a>    <span class="fu">summarize</span>(<span class="at">value =</span> <span class="fu">sum</span>(value,<span class="at">na.rm=</span>T))</span>
<span id="cb30-23"><a href="#cb30-23" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-24"><a href="#cb30-24" aria-hidden="true" tabindex="-1"></a>  <span class="do">## Rename fatalities variable:</span></span>
<span id="cb30-25"><a href="#cb30-25" aria-hidden="true" tabindex="-1"></a>  <span class="fu">colnames</span>(tp)[<span class="fu">colnames</span>(tp) <span class="sc">==</span> <span class="st">"value"</span>] <span class="ot">&lt;-</span> violence_types[i]</span>
<span id="cb30-26"><a href="#cb30-26" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb30-27"><a href="#cb30-27" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Now we can merge it with our main dataset using our group identifiers: </span></span>
<span id="cb30-28"><a href="#cb30-28" aria-hidden="true" tabindex="-1"></a>  df <span class="ot">&lt;-</span> <span class="fu">left_join</span>(df,tp, <span class="at">by =</span> <span class="fu">c</span>(<span class="st">"COUNTRY"</span>,<span class="st">"NAME_1"</span>,<span class="st">"year"</span>))</span>
<span id="cb30-29"><a href="#cb30-29" aria-hidden="true" tabindex="-1"></a>}</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<details>
<summary>
Step-by-Step guide on data aggregation
</summary>
<p>We can collapse the data by province and year via combining the <code>group_by()</code> and <code>summarize()</code> functions from tidyverse. In <code>group_by()</code>, we need to specify the “base variables” of our panel dataset, i.e., space and time. In <code>summarize()</code>, we then specify how to aggregate the data. In conflict studies, we usually care about the total amount of violence. We will therefore sum fatalities over months to arrive at our aggregated dataset.</p>
<p>Because we want to add different variables for each type of violence and append all of them to the same dataset, we need to do this aggregation ten times: Once for the total across types of violence, and then again nine more times subsetting to each type of violence and type of victim. Our code first computed the overall aggregate, and then used a loop to do the aggregation for each type of violence and victim separately.</p>
<p>We now created a dataset with our conflict variables (“deaths_total”, “deaths_civilian”, and “deaths_unknown”), all by type of violence and in the aggregate. Have a look at what the dataset looks like now:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb31"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 234 × 13
# Groups:   COUNTRY, NAME_1 [18]
   COUNTRY NAME_1    year total_fatalities non_state_conflict_deaths_civilians
   &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt;            &lt;dbl&gt;                               &lt;dbl&gt;
 1 Iraq    Al-Anbar  2010              163                                   0
 2 Iraq    Al-Anbar  2011              188                                   0
 3 Iraq    Al-Anbar  2012              113                                   0
 4 Iraq    Al-Anbar  2013              242                                   0
 5 Iraq    Al-Anbar  2014             2039                                   0
 6 Iraq    Al-Anbar  2015             2514                                   0
 7 Iraq    Al-Anbar  2016             3252                                   0
 8 Iraq    Al-Anbar  2017             1000                                   9
 9 Iraq    Al-Anbar  2018              181                                  12
10 Iraq    Al-Anbar  2019               96                                  33
# ℹ 224 more rows
# ℹ 8 more variables: non_state_conflict_deaths_total &lt;dbl&gt;,
#   non_state_conflict_deaths_unknown &lt;dbl&gt;,
#   one_sided_violence_deaths_civilians &lt;dbl&gt;,
#   one_sided_violence_deaths_total &lt;dbl&gt;,
#   one_sided_violence_deaths_unknown &lt;dbl&gt;,
#   state_based_conflict_deaths_civilians &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>We now have 234 observations (18 provinces <span class="math inline">\(\times\)</span> 13 years) and ten different variables for each conflict indicator: one for the total, and one for each type of violence and victim separately. How did we get there? Let’s discuss in detail what the code above just did.</p>
<p>We started by aggregating the dataset lumping all types of violence together. We did this by combining the <code>group_by()</code> and <code>summarize()</code> functions. In <code>group_by()</code>, we specified the <em>grouping variables</em>. These are the variables on which we want <em>R</em> to collapse the dataset. Here, we used <em>year</em> and the combination of the <em>COUNTRY</em> and <em>NAME_1</em> to uniquely identify each province (this is not really necessary here, but if you use data across different countries, you might run into provinces of the same name in different countries). This tells <em>R</em> to aggregate everything to the province-year level.</p>
<p>In the <code>summarize()</code> function, we define <em>which</em> variables we want to aggregate, and <em>how</em> to aggregate them. There are different ways to aggregate data: we can take the average for each province, the maximum, the minimum, or, as we do here, the sum. The choice of the aggregation function depends on the type of variable and your research question. To get an indicator of total violence exposure, it makes sense to take the <em>sum</em> of all fatalities.</p>
<p>The aggregation of the fatalities dataset generated the first part of our dataset. Next, we used a loop to basically do the same procedure again, but separately for each type of violence and victim. To do so, we first generated a vector of all type of violence descriptions in the data with the <code>unique(df_fatal$variable)</code> command, and saved it under the object name <em>violence_types</em>. You see that we have a total of 9 types here. This is because UCDP distinguishes three types of violence (state-based, non-state, one-sided) and gives for each three different fatality counts (civilian deaths, unknown deaths, total deaths).</p>
<p>Let’s now get to the loop. We create a sequence of the same length as our vector with violence types with <code>seq_along(violence_types)</code>, and use <code>i</code> as an index to walk through this sequence. In our specific case here, we will let <code>i</code> walk through the numbers 1 to 9.</p>
<p>The first thing we do in the loop is to prepare our dataset for the aggregation. We do two preparation steps, and stack them behind each other by piping (<code>%&gt;%</code>). The first step is to filter our dataset to one specific type of violence with the <code>filter()</code> function, where <code>violence_types[i]</code> defines the type of violence for each iteration of the loop. Next, we apply the function <code>st_set_geometry(NULL)</code> to drop the geometry feature of our dataset and speed up processing.</p>
<p>Now, we can aggregate the dataset. This is exactly the same as we did above: we use the functions <code>group_by()</code> and <code>summarize()</code> to aggregate everything to the province-year level, this time however only with observations that identify one type of violence.</p>
<p>Afterwards comes an important intermediate step in our loop. We are almost done already, but now face the difficulty of getting the variable names right. Our problem at this step is that we have several datasets that we want to put together, and they both have exactly the same column names. This is by construction, because we do the same steps over and over with the same dataset, only with different filtering choices at the beginning.</p>
<p>This means that we need to <em>rename</em> our variables before appending it to the main dataset. Otherwise, variable names like <em>fatalities</em> would be doubled, and <em>R</em> would automatically rename them to <em>fatalities.X</em> and <em>fatalities.Y</em> and so on. When we want to work with these data later, we would have no idea which variable identifies the events of which type of violence. Therefore, we want to engrave this information in the variable names by renaming the column name called “value” to the type of violence we are working with.</p>
<p>We now finished preparing our dataset and can merge it to the main dataset with the <code>left_join()</code> function. This function combines our main dataset <code>df</code> with the temporary <code>tp</code> dataset that we constructed inside the loop by putting all rows together where the values of all the variables we specify in <code>by = c("COUNTRY","NAME_1","year")</code> are exactly the same. This will make sure that the violence indicators for all provinces and years end up at the right place.</p>
</details>
<p><strong>Preparation of Weather Data</strong></p>
<p>Our conflict data are now ready for the analysis. Before we get there, let’s quickly prepare and add the precipitation data, too.</p>
<p>The preparation of the precipitation data will be very similar to the conflict data above, yet much quicker because we do not have to take care of different aggregations. This is, we only need to:</p>
<ol type="1">
<li>Aggregate the data from the province-month level to the province-year level.</li>
<li>Merge it with our main dataset.</li>
</ol>
<p>Since we already know all the steps, let’s dive right into it and do everything in one go. Note only that we use the <code>mutate()</code> function as the <em>tidyverse</em>-way of creating a new variable, and that we construct the total and the average yearly precipitation as two different aggregated weather indicators:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Prepare Precipitation Data: </span></span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>df_precip <span class="ot">&lt;-</span> df_precip <span class="sc">%&gt;%</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">st_set_geometry</span>(<span class="cn">NULL</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">year =</span> <span class="fu">as.numeric</span>(<span class="fu">format</span>(datetime,<span class="st">"%Y"</span>))) <span class="sc">%&gt;%</span> </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COUNTRY,NAME_1,year) <span class="sc">%&gt;%</span> </span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">precip_sum =</span> <span class="fu">sum</span>(value,<span class="at">na.rm=</span>T),</span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>            <span class="at">precip_mean =</span> <span class="fu">mean</span>(value,<span class="at">na.rm=</span>T))</span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a><span class="do">## Merge with Conflict Data:</span></span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>df <span class="ot">&lt;-</span> <span class="fu">left_join</span>(df,df_precip,<span class="at">by =</span> <span class="fu">c</span>(<span class="st">"COUNTRY"</span>,<span class="st">"NAME_1"</span>,<span class="st">"year"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
<p>Have a look at our dataset now:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>df</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 234 × 15
# Groups:   COUNTRY, NAME_1 [18]
   COUNTRY NAME_1    year total_fatalities non_state_conflict_deaths_civilians
   &lt;chr&gt;   &lt;chr&gt;    &lt;dbl&gt;            &lt;dbl&gt;                               &lt;dbl&gt;
 1 Iraq    Al-Anbar  2010              163                                   0
 2 Iraq    Al-Anbar  2011              188                                   0
 3 Iraq    Al-Anbar  2012              113                                   0
 4 Iraq    Al-Anbar  2013              242                                   0
 5 Iraq    Al-Anbar  2014             2039                                   0
 6 Iraq    Al-Anbar  2015             2514                                   0
 7 Iraq    Al-Anbar  2016             3252                                   0
 8 Iraq    Al-Anbar  2017             1000                                   9
 9 Iraq    Al-Anbar  2018              181                                  12
10 Iraq    Al-Anbar  2019               96                                  33
# ℹ 224 more rows
# ℹ 10 more variables: non_state_conflict_deaths_total &lt;dbl&gt;,
#   non_state_conflict_deaths_unknown &lt;dbl&gt;,
#   one_sided_violence_deaths_civilians &lt;dbl&gt;,
#   one_sided_violence_deaths_total &lt;dbl&gt;,
#   one_sided_violence_deaths_unknown &lt;dbl&gt;,
#   state_based_conflict_deaths_civilians &lt;dbl&gt;, …</code></pre>
</div>
</div>
<p>Our dataset at the province-year level now combines information on fatalities and precipitation. Let’s now add the treecover data and then finally use these data for our empirical analysis. We did not discuss this before, but the tree coverage data are already only a cross section. This means they only hold one value per province, and we won’t have to aggregate anything. Instead, we can simply select the variables we need and merge everything together. We will use the tree-cover data on the left hand side of the merge, because it still has its geometric information (remember that we dropped the geometries from the other files to speed up processing?). By using the tree-cover data on the left hand side of the merge, we receive a dataset with geometries.</p>
<p>We will add one more step though. Because only the conflict data currently vary over time, it does not make much sense to keep everything in a panel format. We will therefore use another aggregation step to get all fatality data to the province level by taking the sum of fatalities across the full time period. We will also use the sum for the precipitation data. This does however not do much, because for precipitation, we anyways only have one value per province, i.e.&nbsp;for the year 2017 that we downloaded. You see this when you inspect the <code>df</code> dataset: Precipitation is missing for all years but 2017. Taking the sum (or any other aggregation function) will just assign the 2017 value to each province. Note finally our use of the <code>across()</code> function.</p>
<details>
<summary>
Details on the <code>across()</code> function
</summary>
<p>Sometimes, you’ll want to aggregate across several variables, not just one. To take a typing shortcut in the <code>summarize()</code> function you can use the <code>across()</code> function inside it. All three functions, <code>group_by()</code>,<code>summarize()</code> and <code>across()</code>, are part of the <em>tidyverse</em>, so they work very well together. It spares you specifying each variable you want to aggregate separately.</p>
<p>When you want to aggregate several variables at the same time (and/or even use more than one aggregation function, see <code>?across()</code> for more information), you can get a much cleaner and shorter code with the <code>across()</code> function. In this function, you first specify a vector with the variable names you want to aggregate. You can even use helper-functions like <code>contains("deaths")</code>, to collect all variables that include the string “deaths”. There are additional function, e.g.&nbsp;<code>starts_with()</code>, and <code>ends_with()</code>, to save you time. Next, you specify the aggregation function via <code>~sum(.x,na.rm=T)</code>. This looks a bit cryptic, but just says:</p>
<ul>
<li>“Apply to all variables” via the <code>~</code> sign.</li>
<li>“Use the function sum()”</li>
<li>The <code>.x</code> tells <em>R</em> that the first argument in the <code>sum()</code> function should be each of the variables.</li>
<li>“Drop missing values before taking the sum” via <code>na.rm=T</code>.</li>
<li>Dropping NAs is important because if NAs are present, <em>R</em> will encounter an error when taking the sum.</li>
</ul>
</details>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="do">### Aggregate df to Province level: </span></span>
<span id="cb36-2"><a href="#cb36-2" aria-hidden="true" tabindex="-1"></a>df_province <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb36-3"><a href="#cb36-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(COUNTRY,NAME_1) <span class="sc">%&gt;%</span> </span>
<span id="cb36-4"><a href="#cb36-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">total_fatalities =</span> <span class="fu">sum</span>(total_fatalities,<span class="at">na.rm=</span>T),</span>
<span id="cb36-5"><a href="#cb36-5" aria-hidden="true" tabindex="-1"></a>            <span class="fu">across</span>(<span class="fu">c</span>(<span class="fu">starts_with</span>(<span class="st">"precip"</span>),<span class="fu">contains</span>(<span class="st">"_deaths_"</span>)), <span class="sc">~</span><span class="fu">sum</span>(.x,<span class="at">na.rm=</span>T)))</span>
<span id="cb36-6"><a href="#cb36-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb36-7"><a href="#cb36-7" aria-hidden="true" tabindex="-1"></a><span class="do">### Merge</span></span>
<span id="cb36-8"><a href="#cb36-8" aria-hidden="true" tabindex="-1"></a>df_final <span class="ot">&lt;-</span> df_trees <span class="sc">%&gt;%</span> </span>
<span id="cb36-9"><a href="#cb36-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(COUNTRY,NAME_1,<span class="at">tree_cover =</span> value) <span class="sc">%&gt;%</span> </span>
<span id="cb36-10"><a href="#cb36-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(df_province,<span class="at">by =</span> <span class="fu">c</span>(<span class="st">"COUNTRY"</span>,<span class="st">"NAME_1"</span>))</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
</div>
</section>
<section id="step-5-visualization" class="level2">
<h2 class="anchored" data-anchor-id="step-5-visualization">Step 5: Visualization</h2>
<p>Before we head to the visualization, we should take a minute and examine our data a bit more closely. This will help us deciding on how we want to graph our data. Let’s start by looking at the distribution of our main variable of interest, <em>total_fatalities</em>.</p>
<details>
<summary>
Some Background on the UCDP Dataset
</summary>
<p>Remember that UCDP defines three types of violence:</p>
<ol type="1">
<li><strong>State-based conflict</strong>: Events of using armed force between two known actors, of which at least one is a government.</li>
<li><strong>Non-state conflict</strong>: Events of using armed force between two known actors, none of which is a government.</li>
<li><strong>One-sided violence</strong>: Events where one formal actor (a government or a non-governmental group) employs armed force against civilians.</li>
</ol>
<p>Note further that all events included in the UCDP GED dataset are assigned to an ongoing conflict that demanded at least 25 battle deaths within a given year. This is, in every year, armed events between, e.g., the Iraqi government and insurgents of the Islamic State (IS) only enter the dataset if the conflict between these two groups exceeded 25 battle deaths in this year. The same goes for the other two types of violence.</p>
</details>
<p>Let’s prepare summary statistics for the country of Iraq across the time span we are looking at and distinguish by type of violence:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb37"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Get Total Fatalilities by Type of Violence:</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>tps <span class="ot">&lt;-</span> <span class="fu">colnames</span>(df_final)[<span class="fu">grepl</span>(<span class="st">"deaths_total"</span>,<span class="fu">colnames</span>(df_final))]</span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Compute the summary statistics of total deaths for each type of violence:</span></span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> <span class="fu">as.list</span>(tps)</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>df_nosf <span class="ot">&lt;-</span> <span class="fu">st_set_geometry</span>(df_final,<span class="cn">NULL</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">data.frame</span>()</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> (k <span class="cf">in</span> <span class="fu">seq_along</span>(tps)) {</span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a>  kk <span class="ot">&lt;-</span> tps[k]</span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>  sm <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Min =</span> <span class="fu">min</span>(df_nosf[,kk],<span class="at">na.rm=</span>T),</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Median =</span> <span class="fu">median</span>(df_nosf[,kk],<span class="at">na.rm=</span>T),</span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Mean =</span> <span class="fu">mean</span>(df_nosf[,kk],<span class="at">na.rm=</span>T),</span>
<span id="cb37-13"><a href="#cb37-13" aria-hidden="true" tabindex="-1"></a>                   <span class="at">Max =</span> <span class="fu">max</span>(df_nosf[,kk],<span class="at">na.rm=</span>T))</span>
<span id="cb37-14"><a href="#cb37-14" aria-hidden="true" tabindex="-1"></a>  summary_stats[[k]] <span class="ot">&lt;-</span> sm</span>
<span id="cb37-15"><a href="#cb37-15" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb37-16"><a href="#cb37-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-17"><a href="#cb37-17" aria-hidden="true" tabindex="-1"></a>summary_stats <span class="ot">&lt;-</span> <span class="fu">do.call</span>(<span class="st">"rbind"</span>,summary_stats)</span>
<span id="cb37-18"><a href="#cb37-18" aria-hidden="true" tabindex="-1"></a><span class="fu">row.names</span>(summary_stats) <span class="ot">&lt;-</span> tps</span>
<span id="cb37-19"><a href="#cb37-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-20"><a href="#cb37-20" aria-hidden="true" tabindex="-1"></a><span class="do">## Have a look:</span></span>
<span id="cb37-21"><a href="#cb37-21" aria-hidden="true" tabindex="-1"></a>summary_stats</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  Min Median       Mean   Max
non_state_conflict_deaths_total     0    0.0   13.05556   138
one_sided_violence_deaths_total     0  122.5  611.72222  4557
state_based_conflict_deaths_total   4  464.0 1836.72222 10559</code></pre>
</div>
</div>
<details>
<summary>
Code Details
</summary>
<p>Let’s quickly recap what we just did in the code above. We first collected the variable names for the total fatalities indicator, for each type of violence as well as the total across all types. All these variables contain the string “deaths_total”, so we use the <code>grepl()</code> function to search for this string in our variable names (<code>colnames(df_final)</code>). By subsetting our column names to those that include this string (by putting the subsetting condition inside the subsettting brackets <code>[]</code>), we get a vector with the four variable names we are interested in. You can do that for each indicator you want, e.g.&nbsp;“deaths_civilians”, by just exchanging the string in the beginning of the code.</p>
<p>Next, we use a loop to calculate the four main descriptive statistics for each of our four variables. We start with two preparation steps:</p>
<ol type="1">
<li><p><code>summary_stats &lt;- as.list(tps)</code> creates a list of the same length as our vector. We will need this list to store the output from each iteration of our loop.</p></li>
<li><p><code>df_nosf &lt;- st_set_geometry(df_final,NULL) %&gt;% data.frame()</code> converts our spatial tibble back to a usual data frame by dropping the geometry and applying the <code>data.frame()</code> function. We need to do this because our basic statistics functions like <code>mean()</code> tend to run into problems when applied to (spatial) tibbles.</p></li>
</ol>
<p>Now we can loop through the four variables by walking through a sequence of the same length as our vector, <code>k in seq_along(tps)</code>. Inside the loop, we first use <code>tps[k]</code> to select the name of the variable from our vector, which is at the k’th position in each iteration. We store it under the object name <code>kk</code>.</p>
<p>Then, we create a data frame where we store the <code>min()</code>, <code>median()</code>, <code>mean()</code>, and <code>max()</code> of the variable <code>kk</code> (i.e.&nbsp;each of the deaths_total variables, iteration by iteration). We then store this data frame at the k’th position in the list we created before the loop: <code>summary_stats[[k]] &lt;- sm</code>.</p>
<p>After the loop, we can turn our summary statistics into a nice table. We do so by:</p>
<ol type="1">
<li>Appending each list-element (i.e.&nbsp;data frame with summary statistics) below each other: <code>summary_stats &lt;- do.call("rbind",summary_stats)</code>.</li>
<li>Adding the variable names as row names to our table: <code>row.names(summary_stats) &lt;- tps</code>.</li>
</ol>
</details>
<p>We now have a nice table that displays the descriptive statistics of the total fatalities by each type of violence. Note that you can do this for any other conflict indicator in your dataset by just exchaning the “deaths_total” string in the beginning of the code snippet.</p>
<p>You already see here in the descriptive statistics that our conflict data are far from normally distributed. This is a typical challenge when working with event data. By their very nature as count variables, they usually follow much closer a Poisson distribution. This somewhat complicates the analysis and especially the visualization.</p>
<p>You see the difficulties even better if we plot the distribution, either as a histogram or as a map:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb39"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Histogram with ggplot()</span></span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_final, <span class="fu">aes</span>(<span class="at">x=</span>total_fatalities)) <span class="sc">+</span> </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">7</span>,<span class="at">fill=</span><span class="st">"steelblue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-27-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb40"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Map with ggplot(): </span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(viridis)</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_final, <span class="fu">aes</span>(<span class="at">fill=</span>total_fatalities)) <span class="sc">+</span> <span class="fu">geom_sf</span>() <span class="sc">+</span> </span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a>      <span class="fu">scale_fill_viridis_c</span>(<span class="at">option=</span><span class="st">"A"</span>,<span class="at">direction=</span><span class="sc">-</span><span class="dv">1</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-27-2.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<details>
<summary>
<code>ggplot()</code> quickly explained
</summary>
<p>The code snippet above uses <code>ggplot()</code> from the <em>tidyverse</em> package to produce a histogram and a map of the number of fatalities in our dataset.</p>
<details>
<summary>
More Details on Histograms
</summary>
<p>Histograms give a very good insight into the distribution of continuous variables. It divides the full range of the data into equally sized bins (you can control either the number or size of bins with the <code>binwidth=</code> or <code>bins=</code> argument in the <code>geom_histogram</code> function). Within each bin, it then counts the number of observations that fall into this bin, and then plots the relative frequency, i.e., the share of observations that fall into a bin.</p>
</details>
<p>The syntax of <code>ggplot()</code> is similar to the general <em>tidyverse</em> syntax, but has a couple of specialties.</p>
<p>You always need to start by defining the plotting parameters inside the <code>ggplot()</code> function itself. You first must define the object from where to take the data to plot (for us, this is <code>df_final</code>). Then, you must define the plotting parameters, also called <em>aesthetics</em>, inside the <code>aes()</code> function, which comes <em>inside</em> the <code>ggplot()</code> function.</p>
<p>The required aesthetics depend on the type of plot you want to make. Usually, we need to define two axis with <code>x=</code> and <code>y=</code>. For a <em>histogram</em>, we only need to define the <code>x=</code> argument, i.e., the variable for which we want to get the histogram. The y-axis will be by default the variable’s frequency because this is what histograms do. So we do not need to specify a variable here.</p>
<p>For the map, it is even more unusual. Here, we do not need to specify any axis, because the x- and y- axes will be our coordinates. Instead, we define the variable we want to display in the <code>fill=</code> argument. This tells <em>R</em> to display our variable as the filling colors of the shapefile’s polygons.</p>
<p>Afterwards, we can close the <code>ggplot()</code> function and continue with a <code>+</code>. In fact, <code>ggplot()</code> allows you to combine as many commands as you want by adding a <code>+</code> each time over and over.</p>
<p>The first additional parameter you should define is the type of plot. Above, this is <code>geom_histogram()</code> for a histogram, and <code>geom_sf()</code> in the second plot for a map. Inside these functions, we <em>can</em> specify additional things, like the (filling) color or the number of bins for a histogram.</p>
<p>These are the parameters you <em>must</em> specify. Afterwards, you can adjust the plot as much as you want by adding additional features with a <code>+</code>. Above, we used for example the <code>scale_fill_viridis_c()</code> function to choose a color palette for our map. Check out the function’s help file to see what color palettes and other things you can choose.</p>
</details>
<p>As you can see from the histogram, the variable is pretty skewed, i.e., we have many observations with comparatively little fatalities, and a handful of observations with very high number of fatalities. That makes it difficult to really grasp the variation that is in the data.</p>
<p>In an empirical analysis, we can account for that either by using specific count data models like Poisson and Negative Binomial regressions, or by categorizing the conflict variable, e.g.&nbsp;into an indicator variable.</p>
<p>For visualization, we also have two options to improve our graphs:</p>
<ol type="1">
<li><strong>Taking the logarithm</strong> smooths the distribution and moves the outliers closer to the rest.</li>
<li><strong>Categorizing</strong> our variable by ranking provinces from low to high conflict intensity.</li>
</ol>
<p>Let’s compare both options. Note however that under option 2, we essentially switch to a categorical variable. This will slightly impact our graphical choices as we a) have to move from a histogram to a <em>barplot</em> and b) adjust the color scheme in our map to discrete.</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Take the logarithm</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>df_final<span class="sc">$</span>ln_fatalities <span class="ot">&lt;-</span> <span class="fu">log</span>(<span class="dv">1</span><span class="sc">+</span>df_final<span class="sc">$</span>total_fatalities)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a><span class="do">## Categorizing with the cut() function.  </span></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a>df_final<span class="sc">$</span>conflict_intensity <span class="ot">&lt;-</span> <span class="fu">as.factor</span>(<span class="fu">cut</span>(df_final<span class="sc">$</span>total_fatalities,</span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>        <span class="at">breaks=</span><span class="fu">c</span>(<span class="sc">-</span><span class="dv">1</span>,<span class="dv">50</span>,<span class="dv">500</span>,<span class="dv">5000</span>,<span class="fu">max</span>(df_final<span class="sc">$</span>total_fatalities))))</span>
<span id="cb41-7"><a href="#cb41-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-8"><a href="#cb41-8" aria-hidden="true" tabindex="-1"></a><span class="do">## Histogram with log variable:</span></span>
<span id="cb41-9"><a href="#cb41-9" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_final, <span class="fu">aes</span>(<span class="at">x=</span>ln_fatalities)) <span class="sc">+</span> </span>
<span id="cb41-10"><a href="#cb41-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>(<span class="at">bins=</span><span class="dv">20</span>,<span class="at">fill=</span><span class="st">"steelblue"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-28-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb42"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Barplot with discrete variable:</span></span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_final, <span class="fu">aes</span>(<span class="at">x=</span>conflict_intensity)) <span class="sc">+</span> </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">fill=</span><span class="st">"steelblue"</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"Conflict Category, (from,to]"</span>,<span class="at">y=</span><span class="st">"#Observations"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-28-2.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<details>
<summary>
More Details on creating categorical variables with <code>cut()</code>
</summary>
<p>We converted our continuous <em>total_fatalities</em> variable to the categorical variable <em>conflict_intensity</em>. Instead of measuring the exact number of fatalities, this categorical variable will just indicate whether an observation is in the category of, e.g., very low or very high fatalities.</p>
<p>Our conversion centers around the <code>cut()</code> function, where we define <em>how</em> to split up the continuous variable into categories using the <code>breaks=</code> argument. Here, we defined our cut breaks with the sequence <code>breaks=c(-1,50,500,5000,max(df_2015$total_fatalities))</code>. This is, we defined a vector (with <code>c()</code>), which starts at <code>-1</code> and moves up in irregular steps of our choosing up to the maximum number of events in our dataset.</p>
<p>It is important to start at some negative value, even though our count variable is bound downwards at zero. This is because the breaks define non-inclusive sets, so e.g.&nbsp;“0” would indicate “anything above zero”. This means that all our zeros would not receive a category, unless we start the lowest category somewhere below zero.</p>
</details>
<details>
<summary>
Background on the logarithm
</summary>
<p>It is common practice to transform skewed continuous variables with a logarithm. This brings their (often log-normal) distribution closer to a normal distribution, which we usually want for analysis and visualization.</p>
<p>Note however that we can not just take the logarithm of the variable. We have many zeros in the data (which is one reason for the variables being skewed), which come from all the provinces that did not see any violence in a year. The problem is though that the logarithm is not defined for non-positive numbers. Therefore, just taking the logarithm of the variable would return missing values for all observations that currently are zeros.</p>
<p>To circumvent that problem, we add a <span class="math inline">\(+1\)</span> to the variable before logging it. This will only marginally change the distribution. However, quite conveniently the logarithm of <span class="math inline">\(1\)</span> is <span class="math inline">\(0\)</span>, in effect giving us back all our zero values.</p>
</details>
<p>There is no really correct way for selecting the cut-offs in the discrete variable. You can of course let <em>R</em> decide the cutoffs and just define the number of categories, or follow quantiles for the breaks. In the end, it is all about finding the best way to visualize the distribution of your data.</p>
<p>Let’s now also look at our maps with the recoded variables:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Map with log variable:</span></span>
<span id="cb43-2"><a href="#cb43-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_final, <span class="fu">aes</span>(<span class="at">fill=</span>ln_fatalities)) <span class="sc">+</span> <span class="fu">geom_sf</span>() <span class="sc">+</span> </span>
<span id="cb43-3"><a href="#cb43-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_c</span>(<span class="at">option=</span><span class="st">"A"</span>,<span class="at">direction=</span><span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Distribution of ln(1+Fatalities)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-29-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb44"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="do">## Map with discrete variable - note the switch to viridis_d():</span></span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_final, <span class="fu">aes</span>(<span class="at">fill=</span>conflict_intensity)) <span class="sc">+</span> <span class="fu">geom_sf</span>() <span class="sc">+</span> </span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_fill_viridis_d</span>(<span class="at">option=</span><span class="st">"A"</span>,<span class="at">direction=</span><span class="sc">-</span><span class="dv">1</span>) <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title=</span><span class="st">"Distribution of Conflict Categories"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-29-2.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>These maps give us a good overview of conflict-related fatalities that occurred in Iraq between 2010 and 2022. Let’s now have a look at the time dimension. Initially, we wanted to see whether we recognize the rise of the Islamic State in Iraq’s conflict data. Since ISL declared their caliphate in Iraq in 2014, we would expect that the conflict trend undergoes a switch around that time.</p>
<p>Let’s first look at the overall time dimension. We’ll turn back to our panel dataset in the <code>df</code> object for this. Do we see a trend break in the time series of fatalities? Note that we need to collapse our dataset to the year level to look at the national variation over time. We will use our old friends <code>group_by()</code> and <code>summarize()</code> for that again:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>df_year <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span> </span>
<span id="cb45-2"><a href="#cb45-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(year) <span class="sc">%&gt;%</span> </span>
<span id="cb45-3"><a href="#cb45-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">fatalities =</span> <span class="fu">sum</span>(total_fatalities)) <span class="sc">%&gt;%</span> </span>
<span id="cb45-4"><a href="#cb45-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ln_fatalities =</span> <span class="fu">log</span>(<span class="dv">1</span><span class="sc">+</span>fatalities))</span>
<span id="cb45-5"><a href="#cb45-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb45-6"><a href="#cb45-6" aria-hidden="true" tabindex="-1"></a><span class="do">## Plot Time Series:</span></span>
<span id="cb45-7"><a href="#cb45-7" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(df_year, <span class="fu">aes</span>(<span class="at">x=</span>year,<span class="at">y=</span>ln_fatalities)) <span class="sc">+</span> <span class="fu">geom_line</span>() <span class="sc">+</span> </span>
<span id="cb45-8"><a href="#cb45-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_x_continuous</span>(<span class="at">breaks =</span> <span class="fu">seq</span>(<span class="dv">2010</span>,<span class="dv">2022</span>,<span class="dv">2</span>)) <span class="sc">+</span> </span>
<span id="cb45-9"><a href="#cb45-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_bw</span>() <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">y =</span> <span class="st">"ln(#Fatalities)"</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="Mapme-Introduction_files/figure-html/unnamed-chunk-30-1.png" class="img-fluid figure-img" width="1152"></p>
</figure>
</div>
</div>
</div>
<p>Do you notice the increase in violence in 2013 and 2014? Seems like the arrival of <em>ISL</em> in Iraq did indeed contribute to a further escalation of violence. To test this hypothesis even further, we could look into the raw conflict data and display violence by actor. We will work with raw conflict event data in another tutorial (LINK HERE?).</p>
</section>
<section id="step-6-simple-regression-analysis" class="level2">
<h2 class="anchored" data-anchor-id="step-6-simple-regression-analysis">Step 6: Simple Regression Analysis</h2>
<p>To close our tutorial, we want to do a simple regression analysis. This analysis will investigate whether the amount of violence in a province correlates with precipitation or tree coverage in a province. We will keep the analysis short, because we dive deeper into regression analysis in our second tutorial on Madagascar.</p>
<p>To run a regression in <em>R</em>, it is convenient to use the <code>feols()</code> function from the <code>fixest</code> package. The syntax is pretty easy. We call our dependent variable, and then declare after <code>~</code> on what explanatory variables we want to regress this dependent variable. The only thing left is to name the dataset that holds these variables. In addition, we will add the <code>se=hetero</code> argument to compute heteroskedasticity-robust standard errors.</p>
<p>We will run three different regressions, and expect each regression’s output using the <code>summary()</code> function. We will first regress the logarithm of fatalities on precipitation, then on tree coverage, and then finally on both together:</p>
<div class="cell">
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(fixest) <span class="co"># To use the feols() function for our regressions.</span></span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>r1 <span class="ot">&lt;-</span> <span class="fu">feols</span>(ln_fatalities <span class="sc">~</span> precip_sum, <span class="at">se=</span><span class="st">"hetero"</span>, <span class="at">data =</span> df_final)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(r1)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: ln_fatalities
Observations: 18
Standard-errors: Heteroskedasticity-robust 
            Estimate Std. Error t value   Pr(&gt;|t|)    
(Intercept) 6.066072   0.675861 8.97532 1.2091e-07 ***
precip_sum  0.000049   0.000036 1.37833 1.8707e-01    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 1.76558   Adj. R2: 0.0603</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>r2 <span class="ot">&lt;-</span> <span class="fu">feols</span>(ln_fatalities <span class="sc">~</span> tree_cover, <span class="at">se=</span><span class="st">"hetero"</span>, <span class="at">data =</span> df_final)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(r2)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: ln_fatalities
Observations: 18
Standard-errors: Heteroskedasticity-robust 
             Estimate Std. Error  t value   Pr(&gt;|t|)    
(Intercept)  6.979065   0.467187 14.93847 8.1265e-11 ***
tree_cover  -0.000462   0.000078 -5.88594 2.2998e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 1.73608   Adj. R2: 0.091436</code></pre>
</div>
<div class="code-copy-outer-scaffold"><div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>r3 <span class="ot">&lt;-</span> <span class="fu">feols</span>(ln_fatalities <span class="sc">~</span> precip_sum <span class="sc">+</span> tree_cover, <span class="at">se=</span><span class="st">"hetero"</span>, <span class="at">data =</span> df_final)</span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(r3)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div class="cell-output cell-output-stdout">
<pre><code>OLS estimation, Dep. Var.: ln_fatalities
Observations: 18
Standard-errors: Heteroskedasticity-robust 
             Estimate Std. Error  t value   Pr(&gt;|t|)    
(Intercept)  6.317655   0.678256  9.31457 1.2612e-07 ***
precip_sum   0.000045   0.000036  1.25355 2.2919e-01    
tree_cover  -0.000431   0.000077 -5.59984 5.0669e-05 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
RMSE: 1.63556   Adj. R2: 0.139846</code></pre>
</div>
</div>
<p>Our regressions show a significantly negative correlation between fatalities and tree coverage. Provinces with more ha covered by trees saw significantly less conflict fatalities. We do not see a significant correlation between fatalities and precipitation. Be however careful how you interpret this finding. The significant correlation does not tell us that more trees <em>cause</em> less violence. Instead, many other variables that we did not account for, e.g.&nbsp;urbanization and population density, might correlate with violence <em>and</em> tree coverage.</p>
</section>


</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
</div> <!-- /content -->




</body></html>